### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by mtaivalmaa** [cinamo/asterisk-operator-panel#1]
Hello,

I am interested in giving your operator panel a try.

on npm install i get the following..  any ideas?  I am running ubuntu 16

npm WARN lifecycle asterisk-operator-panel@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) asterisk-operator-panel@0.1.0 bower install /usr/src/asterisk-operator-panel

Kind Regards,

Mike

**Comment by cinamo** [comment]
Just to be sure, do you have `bower` installed in your path?

**Comment by cinamo** [comment]
I get the same error on my Ubuntu 16.04 install. Just run `bower install` manually on the command line after `npm install`, which will retrieve all Bower assets for the frontend.
